name: AWS - Cria food-cliente-db

on:
  workflow_dispatch:

jobs:
  preapare-dependencies:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: food-cliente-db

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Load environment variables
      uses: thaind0/envfile@v1
      with:
        secrets: ${{ toJSON(secrets) }}
        override: false # prevent overriding VPC_ID | LAMBDA_SG_ID -> don't create the env variables
        file: .env

    - name: Get VPC ID
      id: get-vpc-id
      run: |
        VPC_ID=$(aws ec2 describe-vpcs --filters "Name=tag:Name,Values=${{ secrets.VPC_NAME }}" --query "Vpcs[0].VpcId" --output text)
        echo "VPC_ID=$VPC_ID" >> $GITHUB_ENV

    - name: Get Lambda Security Group ID
      id: get-lambda-sg-id
      run: |
        LAMBDA_SG_ID=$(aws ec2 describe-security-groups --filters "Name=group-name,Values=${{ secrets.LAMBDA_SG_NAME }}" --query "SecurityGroups[0].GroupId" --output text)
        echo "LAMBDA_SG_ID=$LAMBDA_SG_ID" >> $GITHUB_ENV

    - name: Get EKS Cluster ID
      id: get-eks-cluster-id
      # CLUSTER_SG_ID=$(aws ec2 describe-security-groups --filters "Name=tag:Name,Values=${{ secrets.CLUSTER_NAME }}-sg" --query "SecurityGroups[0].GroupId" --output text)
      run: |
        CLUSTER_SG_ID=$(aws ec2 describe-security-groups --filters "Name=tag:aws:eks:cluster-name,Values=${{ secrets.CLUSTER_NAME }}" --query "SecurityGroups[0].GroupId" --output text)
        echo "CLUSTER_SG_ID=$CLUSTER_SG_ID" >> $GITHUB_ENV

    - name: Fail if VPC_ID is empty or undefined
      if: ${{ env.VPC_ID == '' || env.VPC_ID == 'None' }}
      run: |
        echo "VPC_ID is empty. Exiting workflow."
        exit 1

    - name: Fail if LAMBDA_SG_ID is empty or undefined
      if: ${{ env.LAMBDA_SG_ID == '' || env.LAMBDA_SG_ID == 'None'  }}
      run: |
        echo "LAMBDA_SG_ID is empty. Exiting workflow."
        exit 1

    - name: Fail if CLUSTER_SG_ID is empty or undefined
      if: ${{ env.CLUSTER_SG_ID == '' || env.CLUSTER_SG_ID == 'None'  }}
      run: |
        echo "CLUSTER_SG_ID is empty. Exiting workflow."
        exit 1

    - name: Overwrite .env variable
      if: success()
      run: |
        echo "VPC_ID=${{ env.VPC_ID }}" >> .env
        echo "LAMBDA_SG_ID=${{ env.LAMBDA_SG_ID }}" >> .env
        echo "CLUSTER_SG_ID=${{ env.CLUSTER_SG_ID }}" >> .env

    - name: Setup Terraform
      if: success()
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      if: success()
      run: |
        echo BUCKET NAME=${{ secrets.AWS_BUCKET_NAME }}
        terraform init -upgrade -reconfigure -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=food-cliente-db.tfstate" -backend-config="region=${{ secrets.AWS_REGION }}"

    - name: Terraform Validate
      if: success()
      run: terraform validate

    - name: Terraform Plan
      if: success()
      run: bash terraform.sh plan

    - name: Terraform Apply
      if: success()
      run: bash terraform.sh apply -auto-approve
